In [2]:
import math #the "import" function allows to import, in this example... the math library that is within my anaconda program

In [3]:
math.pi #so, when we try to use a function within the "math" libary we must type first the library followed "." and the function "math.pi"

3.141592653589793

In [4]:
math.e

2.718281828459045

In [5]:
math.inf

inf

In [6]:
math.ceil(7.8)

8

In [7]:
math.floor(2.5)

2

In [8]:
float_list = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1] #in this example we eant to sum a list of floating numbers

In [9]:
sum(float_list) #the result wont be as much as accurate as we want if we use the "sum" function

0.9999999999999999

In [10]:
math.fsum(float_list) #to get an accurate sum of floating numbers we use the library "math" "." and the fucntion "fsum" wich refeers to the sum of floating numbers and last the list "float_list" wich is the one we want to sum.

1.0

In [11]:
math.gcd(30, 20) #here we are telling the code to give us the greatest common denominator (gcd) for 30 and 20 so the result will we 10

10

In [12]:
math.gcd(3343, 223) #in this example there is no gcd for number 3343 and 223 so it is 1 the result

1

In [13]:
!pip install numpy #to install a library you must use "!" exclamation sign followed by "install" and the library we want to install in this case "numpy"

#so in this case as we use jupiter notebook it is already intalled and we can prove it by the message "Requirement already satisfied"

Defaulting to user installation because normal site-packages is not writeable


In [14]:
import numpy as np #numpy library is also known as "np" so when importing the library you must declare it "as" the alias

In [15]:
some_list = [1, 2, 3, 4, 5, 6, 7]

type(some_list) #here we have a "build up" list in order to make an example of using numpy

list

In [16]:
some_array = np.array(some_list) #here we build a np array and assigned the name of "some_array", in order to make a list an array we must type "np.array" followed by the list inside parethesis ()

type(some_array) #so we can prove that "some_array" is a numpy array by looking at the "type" of data

#the "nd" in "ndarray" stands for n-dimensional = multidimensional

numpy.ndarray

In [17]:
some_array #so as we can see... we have the same values as the list before but in a diferent format

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
ones_array = np.ones(5) #here is an example of a quick build array by writting "ones" and number (5) it would show an array of "1." numbers repeated 5 times

ones_array

array([1., 1., 1., 1., 1.])

In [20]:
range_array = np.arange(8) #by using "arange" and the range of "8" we tell our code to go from 0 to 7 (8 elements total) in a array

range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
reshape_array = range_array.reshape(2, 4) #in this case we made a re-shape of an array, 2 lists of 4 elements each (0, 1, 2, 3) and (4, 5, 6, 7)

reshape_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
reshape_array = range_array.reshape(4, 2) # here we have the same example but with inversed numbers 4 lists of 2 elements each

reshape_array # remember in order to make this reshape function works must be compatible numbers of columns and elements

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [23]:
random_array = np.random.random((4, 5)) #we can make a random lists of numbers by using the "np.random" function and would give you a random number between 1-0, so here we can see we made 4 lists of 5 elements each.

random_array

array([[0.80479813, 0.26627035, 0.68806297, 0.23919843, 0.55686145],
       [0.22103532, 0.70326219, 0.38940048, 0.57962112, 0.11867226],
       [0.10133122, 0.86116951, 0.45413705, 0.23506114, 0.29469241],
       [0.01561076, 0.8297357 , 0.22438409, 0.07917118, 0.0394035 ]])

In [26]:
range_array #here we have the original "range_array" function with his elements

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
mean = np.mean(range_array) #to calculate the mean we use "np.mean" function

mean

3.5

In [28]:
median = np.median(range_array) #this is the formula to calculate the "median"

median

3.5

In [29]:
var = np.var(range_array) #this function is to calculate the "variance"

var

5.25

In [30]:
std = np.std(range_array) #this funciton is to calculate the standar deviation "std"

std

2.29128784747792

# USING PANDAS IN DATA ANALYSIS

In [31]:
!pip install pandas #tis is the script to install pandar but it allready comes with the anaconda distrubition

Defaulting to user installation because normal site-packages is not writeable


In [32]:
import pandas as pd #this is how we import pandas and always with the nickname "ps"

In [35]:
df = pd.DataFrame ({
                   "name" : ["eri", "mary", "rudy", "titi", "guerito"],
                   "gender": ["male", "female", "male", "female", "male"],
                   "age": [30, 28, 33, 2, 6],
                   })

# in pandas the data is placed in "DataFrames" wich is rows and columns and is how can python can read it... this example shows
# 3 columns (name, gender, age) each one with his corresponding elements. 

In [36]:
df #here we can see how the python code is now placed as a table

name  gender  age
0      eri    male   30
1     mary  female   28
2     rudy    male   33
3     titi  female    2
4  guerito    male    6

In [37]:
df.describe() #here by the "describe" function we can se an statisticall review of all the numbers inside the mentionated table in this case the "df" table

age
count   5.00000
mean   19.80000
std    14.60137
min     2.00000
25%     6.00000
50%    28.00000
75%    30.00000
max    33.00000

In [38]:
subset_df = df [["name", "age"]] #you can choose the columns you want to view by using the "subset" function

subset_df #in this example we told our code we just want to view "name" and "age" in our data frame 

name  age
0      eri   30
1     mary   28
2     rudy   33
3     titi    2
4  guerito    6

In [39]:
groupby_df = df.groupby(by="gender").count() #here is how we can group and count realated to a charecteristic, in this example it is "gender" and we want our program to count it

groupby_df.head() #so, we use the "groupby function" and tell the code to count "gender"

name  age
gender           
female     2    2
male       3    3